### ISSUE TITLE
Build fails: error: explicit specialization of undeclared template class 'is_container_adaptor_like'

### ISSUE THREAD

**Issue by yurivict** [ossia/score#1479]
```
In file included from /usr/ports/multimedia/ossia-score/work/ossia-score-3.1.11/3rdparty/libossia/src/ossia/network/domain/detail/domain_impl.cpp:6:
/usr/ports/multimedia/ossia-score/work/ossia-score-3.1.11/3rdparty/libossia/src/ossia/network/value/format_value.hpp:14:29: error: explicit specialization of undeclared template class 'is_container_adaptor_like'
template <typename T> class is_container_adaptor_like<boost::container::flat_set<T>>
                            ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Version: 3.1.11
clang-15
FreeBSD 13.2

**Comment by jcelerier** [comment]
hmm, can you share the CMakeCache.txt ? I saw this when using libfmt 9.x, it is fixed in 10.x

**Comment by yurivict** [comment]
[CMakeCache.txt](https://people.freebsd.org/~yuri/ossia-score-3.1.11-CMakeCache.txt)

We use libfmt-9.1.0.
libfmt-10.x isn't supported by spdlog.

**Comment by jcelerier** [comment]
hmmm here it works with recent spdlog commits... since https://github.com/gabime/spdlog/pull/2744

**Comment by yurivict** [comment]
> hmmm here it works with recent spdlog commits

Yes, they recently fixed this, but fixes aren't released.

**Comment by yurivict** [comment]
@jcelerier 
The above spdlog PR was merged and is now supposedly in their release spdlog-1.12.0, but this ossia error is still present.
Do you know what might be causing it?

ossia-score-3.1.11
spdlog-1.12.0
libfmt-9.1.0
clang-15
FreeBSD 13.2

**Comment by jcelerier** [comment]
@yurivict the root issue comes from fmt, it's fixed in https://github.com/fmtlib/fmt/releases/tag/10.0.0

**Comment by luzpaz** [comment]
@yurivict can you try to reproduce with updated fmtlib ?

**Comment by luzpaz** [comment]
bumping

**Comment by jcelerier** [comment]
double-bumping

**Comment by jcelerier** [comment]
ok, assuming this is fixed through fmt / spdlog updates. please reopen if not :)
